pure_pursuit:
  ros__parameters:
    odom_topic: "/ego_racecar/odom"
    path_topic: "/Path"
    car_refFrame: "ego_racecar/base_link"
    global_refFrame: "map"
    drive_topic: "/drive"
    test_mode: False
    drive_test_topic: "/drive_test"
    rviz_current_waypoint_topic: "/current_waypoint"
    rviz_lookahead_waypoint_topic: "/lookahead_waypoint"
    rviz_speed_offset_waypoint_topic: "/speed_offset_waypoint"

    # Pure Pursuit Parameters
    # Lookahead is computed using the following: lookahead = min(max(min_lookahead, max_lookahead * curr_velocity / lookahead_ratio), max_lookahead);
    min_lookahead: 0.5
    max_lookahead: 3.0 # lookahead when the car is going around max velocity
    lookahead_ratio: 8.0 # approximately the max velocity
    speed_profile_distance_offset: 0.0
    drive_output_rate_hz: 50.0
    steer_latest_blend: 0.10
    steer_large_change_blend: 0.55
    steer_blend_change_threshold_deg: 10.0
    speed_latest_blend: 0.90
    K_p: 0.5
    steering_limit: 25.0
    steering_expo_gain: 0.0
    steering_expo_curve: 2.0
    velocity_percentage: 1.0 # the limit, can only do 1 lap with clean tires
    steer_reduction_speed_threshold: 5.0 # m/s
    steer_reduction_constant_coef: 0.85
    steer_reduction_linear_coef: 0.03
    steer_reduction_min_scale: 0.3
    speed_reduction_steer_angle_deg: 12.0
    max_allowed_steer_drop_deg: 5.0
    speed_reduction_adjust: 0.0
    speed_reduction_prev_scale: 0.0

waypoint_visualizer_node:
  ros__parameters:
    path_topic: "/Path"
    rviz_waypoints_topic: "/waypoints"
